this is third commit
MKS435364758/studentCourseProject pull request #3
Opened 2023-02-13 17:17 UTC by MKS435364758

new lines are add

2023-02-13 17:19 UTC, mxs14520 requested changes

2023-02-13 17:19 UTC, mxs14520 commented on newFile.txt
> +//this is second comment
add this line

2023-02-13 17:19 UTC, MKS435364758 commented on newFile.txt
> +//this is second comment
ok its done

2023-02-13 17:23 UTC, mxs14520 approved these changes

2023-02-13 17:24 UTC, merged

2023-03-03 21:49 UTC, MKS435364758 commented
nice